#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Test.Resource", IsApplication=true)]

namespace Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int gray = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f04000b
			public const int button_height = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int button_width = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int imagesize_small = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int margin_large = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int margin_medium = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int margin_small = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int padding_large = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int padding_medium = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int padding_top = 2130968584;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowright = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int camera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int company = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int contact = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int discover = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int form = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int formtop = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int numbers = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int people = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int send = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int send_inactive = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int services = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sicpa = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int stories = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int venture = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001d
			public const int btn_contact = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int btn_main = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int btn_stories = 2131034140;
			
			// aapt resource value: 0x7f050012
			public const int button1 = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int checkBox1 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int checkBox2 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int checkBox3 = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int fragment = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int imageButton1 = 2131034125;
			
			// aapt resource value: 0x7f05001f
			public const int imebtn_back = 2131034143;
			
			// aapt resource value: 0x7f050014
			public const int imebtn_discover = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int imebtn_numbers = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int imebtn_people = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int imebtn_services = 2131034135;
			
			// aapt resource value: 0x7f050022
			public const int imebtn_story = 2131034146;
			
			// aapt resource value: 0x7f05001a
			public const int imebtn_venture = 2131034138;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout2 = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout3 = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout4 = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout5 = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int linearLayout6 = 2131034136;
			
			// aapt resource value: 0x7f050020
			public const int pdfv_story = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int rccv_stories = 2131034145;
			
			// aapt resource value: 0x7f050001
			public const int relativeLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int scrollView1 = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int spinner1 = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int textView2 = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int textView3 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int textView4 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int textView5 = 2131034129;
			
			// aapt resource value: 0x7f05001e
			public const int toolbar1 = 2131034142;
			
			// aapt resource value: 0x7f050002
			public const int tv_hello = 2131034114;
			
			// aapt resource value: 0x7f050023
			public const int vdv_story = 2131034147;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Contact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Pdf = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Stories = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Stories1 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Story = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Video = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int branchHint = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int checkboxDiscuss = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int checkboxFindJob = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int checkboxOtherReason = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int checkboxSayHi = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int company = 2131165185;
			
			// aapt resource value: 0x7f07000e
			public const int companyHint = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int contact = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int emailHint = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int firstNameHint = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int hello = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int help = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int lastNameHint = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int note = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int personalData = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int positionHint = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int send = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int stories = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int takePicture = 2131165195;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
